Hooks release
k-kryukov/PRE_COMMIT pull request #2
Opened 2022-06-21 16:11 UTC by k-kryukov

Made single folder for all source files of hooks
Included hook tests which allows to test basic usage of hooks
Added PEP8 support and changed hooks in order to meet PEP8 requirements

2022-06-21 16:29 UTC, alexeyandriyash commented on README.md
> +!!! (UTILITIES ARE EXECUTED ONLY FOR FILE IN INDEX)
Is it true? May be for every file was changed?

2022-06-21 16:34 UTC, alexeyandriyash commented on git_hooks_source_files/commit-msg.py
> +        print(green_color + "Good Commit!" + color_off)
Let's make it silent if everything is perfect

2022-06-21 16:34 UTC, alexeyandriyash commented on git_hooks_source_files/hooks_tests/hooks_tests.sh
> +file_path=".git/hooks_tests/testHooksLog"
could you add this file to .gitignore please?

2022-06-21 16:35 UTC, alexeyandriyash commented on git_hooks_source_files/hooks_tests/hooks_tests.sh
> +
`set -e` to stop execution if something was failded

2022-06-21 16:40 UTC, alexeyandriyash commented on git_hooks_source_files/installator.py
>      os.system(f'cp -r {path}/git_hooks_source_files/.clang-format {path}')
without `-r` flag `hooks_tests` folder wouldn't be copied

2022-06-21 16:42 UTC, alexeyandriyash commented on git_hooks_source_files/installator.py
> +    path_to_repo = sb.check_output(['pwd']).decode('UTF-8').strip()
To get the current working directory you could use
```
import os
cwd = os.getcwd()
```

2022-06-21 16:46 UTC, alexeyandriyash commented on git_hooks_source_files/pre-commit.py
> +    os.system('git status --short > .git/hooks/current_state_of_index')
for a future needs https://gitpython.readthedocs.io/en/stable/tutorial.html

2022-06-21 16:52 UTC, alexeyandriyash commented on git_hooks_source_files/prepare-commit-msg.py
> +        branch = "1234"
You should somehow inform that you wasn't able to get branch name.
Does this script execution have any sense after this exception?

2022-06-21 16:59 UTC, alexeyandriyash commented
![изображение](https://user-images.githubusercontent.com/17828824/174856478-8dabbe07-db8f-44a0-88d3-ff6e46274462.png)

2022-06-21 17:01 UTC, alexeyandriyash commented
Some small things should be fixed

2022-06-22 08:44 UTC, k-kryukov commented on README.md
>  Activation/deactivation:
done

2022-06-22 08:53 UTC, k-kryukov commented on git_hooks_source_files/commit-msg.py
> +        print(green_color + "Good Commit!" + color_off)
done

2022-06-22 09:10 UTC, k-kryukov commented on git_hooks_source_files/hooks_tests/hooks_tests.sh
> +file_path=".git/hooks_tests/testHooksLog"
done

2022-06-22 09:11 UTC, k-kryukov commented on README.md
> +!!! (UTILITIES ARE EXECUTED ONLY FOR FILE IN INDEX)
RFC

2022-06-22 09:21 UTC, k-kryukov commented on git_hooks_source_files/hooks_tests/hooks_tests.sh
> +
done

2022-06-22 09:27 UTC, k-kryukov commented on git_hooks_source_files/installator.py
>      os.system(f'cp -r {path}/git_hooks_source_files/.clang-format {path}')
yeah, such as pre-commit-message/pre-commit-message-helper and other info files which contains messages given to user
hooks_tests is a single folder which shouldn't be copied

2022-06-24 11:56 UTC, TheSalvator commented
.clang-format не нужен, уже есть в проекте

2022-06-24 12:16 UTC, TheSalvator requested changes

2022-06-24 12:16 UTC, TheSalvator commented on git_hooks_source_files/commit-msg
> +        warning_text = open(warning_text_path).read()
Добавь контекстный менеджер

2022-06-24 12:16 UTC, TheSalvator commented on git_hooks_source_files/pre-commit
>      for i in range(len(s)):
for index, letter in enumerate(s): ...

2022-06-24 12:16 UTC, TheSalvator commented on git_hooks_source_files/pre-commit
>      f = open(".git/hooks/current_state_of_index", 'r')
контекстный менеджер

2022-06-24 12:16 UTC, TheSalvator commented on git_hooks_source_files/pre-commit
> +    text_json = open(".git/hooks/utilities-config.json")
with open ...

2022-06-24 12:16 UTC, TheSalvator commented on git_hooks_source_files/prepare-commit-msg
> +    commit_msg_config = json.load(open(commit_msg_cfg_path))[hook_name]
with open ...

2022-06-24 12:42 UTC, k-kryukov commented on git_hooks_source_files/commit-msg
> +        warning_text = open(warning_text_path).read()
done

2022-06-24 13:18 UTC, merged